services:
  saos-project:
    build: .
    volumes:
      - "./uploads:/uploads"
    env_file: ".env"
    ports:
      - 8080:5000
    networks:
      saos-network:
        aliases:
          - app.saos.local

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    ports:
      - 8081:8080
    env_file: ".env"
    command: [
      "start-dev",
      "--proxy-headers", "xforwarded",
      "--hostname-strict=false",
      "--hostname", "https://keycloak.saos.local",
      "--hostname-backchannel-dynamic", "true",
      "--http-port", "80",
      "--log", "console,syslog",
      "--log-level", "INFO",
      "--log-syslog-endpoint", "logstash:514"
    ]
    volumes:
      - ./keycloak:/opt/keycloak/data/
    networks:
      saos-network:
        aliases:
          - keycloak.saos.local

  caddy:
    image: caddy:2.8.4
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - saos-network

  db:
    image: postgres:17.5
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: ".env"
    networks:
      - saos-network

  db-webui:
    image: clidey/whodb
    restart: unless-stopped
    ports:
      - 8082:8080
    env_file: ".env"
    networks:
      - saos-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.audit.enabled=true
    env_file: ".env"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - saos-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    env_file: ".env"
    ports:
      - "5601:5601"
    networks:
      - saos-network
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.0
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro,Z
      - ./logstash/config/jvm.options:/usr/share/logstash/config/jvm.options:ro,Z
    ports:
      - "5044:5044"
    networks:
      - saos-network
    depends_on:
      - elasticsearch

volumes:
  pgdata:
  caddy_config:
  caddy_data:
  elasticsearch-data:
    driver: local

networks:
  saos-network:
    driver: bridge