services:
  saos-project:
    build: .
    ports:
      - 8080:5000
    extra_hosts:
      - host.docker.internal:host-gateway

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    ports:
      - 8081:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin1
    command:
      - start-dev
    volumes:
      - ./keycloak:/opt/keycloak/data/

  db:
    image: postgres:17.5
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  db-webui:
    image: clidey/whodb
    restart: unless-stopped
    ports:
      - 8082:8080
    environment:
      - WHODB_POSTGRES_1={"host":"db","user":"admin","password":"admin","database":"postgres"}

volumes:
  pgdata: